### ISSUE TITLE
Add comments + emoji reactions

### ISSUE THREAD

**Issue by tinakapoor** [imransilvake/Slack-App-Clone#1]
Hi, I love the app. I'm new to react and learning a lot from you. I was wondering if you can add a feature where clicking on a message opens a new page filled with comments and lets you comment on the message. You could also add a feature to add different emojis on each message or comment like facebook has. Thanks!

**Comment by imransilvake** [comment]
@tinakapoor sorry, I build this a while ago for learning purposes and have no plans to add any new functionality to it.
